/**
 * Demo fixtures for the MicroWar landing page.
 *
 * Nothing here is real data. House names are invented for the game and are
 * deliberately derived from places, not institutional trademarks (PLAN.md §6.4).
 * PI names are fictional.
 */
import type {
  Card,
  Challenge,
  Fixture,
  House,
  Organism,
  OrganismId,
  Season,
  Stream,
  TickerItem,
  Track,
} from "./types";

export const ORGANISMS: Record<OrganismId, Organism> = {
  ecoli: {
    id: "ecoli",
    name: "Escherichia coli",
    short: "E. coli",
    glyph: "◆",
    accent: "#b8ff3c",
    colourRationale: "Classic lab-strain green; the LB-plate association.",
    role: "The workhorse — production chassis",
  },
  strep: {
    id: "strep",
    name: "Streptococcus spp.",
    short: "Strep",
    glyph: "◈",
    accent: "#ff3b5c",
    colourRationale: "β-hemolysis clears blood agar crimson.",
    role: "The duelist — hemolysis & bacteriocins",
  },
  pseudo: {
    id: "pseudo",
    name: "Pseudomonas aeruginosa",
    short: "P. aeruginosa",
    glyph: "◉",
    accent: "#2fe6d6",
    colourRationale: "Pyocyanin is literally blue-green; pyoverdine fluoresces.",
    role: "The artist — pigments & antagonism",
  },
  acineto: {
    id: "acineto",
    name: "Acinetobacter baumannii",
    short: "A. baumannii",
    glyph: "◇",
    accent: "#ffb020",
    colourRationale: "Desiccation-resistant; the priority AMR target.",
    role: "The survivor — robustness & AMR target",
  },
};

export const TRACKS: Record<Track["id"], Track> = {
  "product-titer": {
    id: "product-titer",
    name: "Titer — Product",
    objective: "Maximise yield of a target molecule",
    readout: "Colorimetric analysis, OD turbidity",
    unit: "mg/L",
    instrument: "HT imaging + microtiter",
  },
  "antibiotic-titer": {
    id: "antibiotic-titer",
    name: "Titer — Antibiotic",
    objective: "Maximise inhibition of a reference indicator strain",
    readout: "Zone-of-inhibition diameter",
    unit: "mm halo",
    instrument: "HT imaging, petri",
  },
  chroma: {
    id: "chroma",
    name: "Chroma",
    objective: "Aesthetic colour and pattern expression",
    readout: "Timelapse RGB segmentation + jury vote",
    unit: "chroma",
    instrument: "Smart Incubator timelapse",
  },
  arena: {
    id: "arena",
    name: "Arena",
    objective: "Out-compete an opponent strain in co-culture",
    readout: "Differential counts, antagonism assay",
    unit: "CFU ×10³",
    instrument: "Timelapse + differential AI model",
  },
  "media-cup": {
    id: "media-cup",
    name: "Media Cup",
    objective: "Best medium for a fixed reference strain",
    readout: "Growth kinetics, radial growth rate",
    unit: "mm/h",
    instrument: "Timelapse, kinetic",
  },
  robustness: {
    id: "robustness",
    name: "Iron Gut",
    objective: "Survive stress and preservative panels",
    readout: "Viable count retention",
    unit: "% retained",
    instrument: "HT imaging",
  },
  sprint: {
    id: "sprint",
    name: "Sprint",
    objective: "Fastest µmax under defined conditions",
    readout: "Growth kinetics",
    unit: "µmax h⁻¹",
    instrument: "Timelapse, 10-min interval",
  },
  purity: {
    id: "purity",
    name: "Purity",
    objective: "Cleanest co-culture, lowest contamination",
    readout: "Differential counts",
    unit: "% pure",
    instrument: "HT imaging",
  },
};

export const SEASON: Season = {
  number: 3,
  name: "The Pyocyanin Open",
  houses: 32,
  continents: 4,
  plates: 1280,
  // Rolling target: the Countdown component pushes it forward a week at a
  // time if the built value is already in the past, so the demo never shows
  // a stale, negative countdown.
  sealedOpensAt: "2026-10-09T18:00:00Z",
  strapline: "The open league for antimicrobial and bioproduction discovery.",
};

type HouseSeed = [
  slug: string,
  name: string,
  institution: string,
  city: string,
  country: string,
  cc: string,
  lat: number,
  lon: number,
  primary: string,
  secondary: string,
  organism: OrganismId,
  elo: number,
];

const HOUSE_SEEDS: HouseSeed[] = [
  ["davidoffs", "The Davidoffs", "UC Davis", "Davis", "United States", "US", 38.5, -121.7, "#e8c46a", "#0f2a52", "pseudo", 1842],
  ["lyngby-lysogens", "The Lyngby Lysogens", "DTU Lyngby", "Lyngby", "Denmark", "DK", 55.8, 12.5, "#9fd8ff", "#12203a", "ecoli", 1811],
  ["wageningen-wildtypes", "The Wageningen Wildtypes", "Wageningen", "Wageningen", "Netherlands", "NL", 52.0, 5.7, "#4caf50", "#10261a", "ecoli", 1734],
  ["zurich-zymurgists", "The Zürich Zymurgists", "ETH Zürich", "Zürich", "Switzerland", "CH", 47.4, 8.5, "#ffffff", "#c8102e", "ecoli", 1798],
  ["kensington-kinetics", "The Kensington Kinetics", "Imperial College London", "London", "United Kingdom", "GB", 51.5, -0.2, "#7a1f2b", "#1a0a0d", "strep", 1776],
  ["planck-plasmids", "The Planck Plasmids", "Max Planck", "Munich", "Germany", "DE", 48.1, 11.6, "#6b7a8f", "#1b2230", "acineto", 1759],
  ["solna-selectors", "The Solna Selectors", "Karolinska", "Solna", "Sweden", "SE", 59.4, 18.0, "#1f4fd8", "#0d1633", "strep", 1701],
  ["hongo-halos", "The Hongo Halos", "University of Tokyo", "Tokyo", "Japan", "JP", 35.7, 139.8, "#4b3fa8", "#150f33", "acineto", 1788],
  ["tsinghua-titers", "The Tsinghua Titers", "Tsinghua", "Beijing", "China", "CN", 40.0, 116.3, "#e34234", "#2a0e0b", "ecoli", 1767],
  ["kent-ridge-colonies", "The Kent Ridge Colonies", "NUS Singapore", "Singapore", "Singapore", "SG", 1.3, 103.8, "#1fa89c", "#0b2624", "pseudo", 1722],
  ["daejeon-diffusers", "The Daejeon Diffusers", "KAIST", "Daejeon", "South Korea", "KR", 36.4, 127.4, "#8fa3b8", "#1b232c", "acineto", 1688],
  ["oxford-oxidants", "The Oxford Oxidants", "Oxford", "Oxford", "United Kingdom", "GB", 51.8, -1.3, "#002147", "#8fb3e0", "strep", 1745],
  ["cam-conjugators", "The Cam Conjugators", "Cambridge", "Cambridge", "United Kingdom", "GB", 52.2, 0.1, "#a3c1e6", "#0f1c2c", "ecoli", 1752],
  ["delft-dilutions", "The Delft Dilutions", "TU Delft", "Delft", "Netherlands", "NL", 52.0, 4.4, "#2b5fb3", "#0d1a33", "pseudo", 1710],
  ["ghent-gradients", "The Ghent Gradients", "Ghent", "Ghent", "Belgium", "BE", 51.1, 3.7, "#ffb020", "#2a1c05", "pseudo", 1693],
  ["goteborg-glycolytics", "The Göteborg Glycolytics", "Chalmers", "Göteborg", "Sweden", "SE", 57.7, 12.0, "#2e8b74", "#0b2620", "ecoli", 1677],
  ["lausanne-lysates", "The Lausanne Lysates", "EPFL", "Lausanne", "Switzerland", "CH", 46.5, 6.6, "#dc143c", "#2a0810", "strep", 1730],
  ["coyoacan-colonies", "The Coyoacán Colonies", "UNAM", "Mexico City", "Mexico", "MX", 19.3, -99.2, "#ff8c1a", "#2b1505", "acineto", 1664],
  ["table-mountain-titrators", "The Table Mountain Titrators", "Cape Town", "Cape Town", "South Africa", "ZA", -33.9, 18.4, "#f06aa8", "#2a0f1e", "pseudo", 1702],
  ["powai-plasmids", "The Powai Plasmids", "IIT Bombay", "Mumbai", "India", "IN", 19.1, 72.9, "#ff9933", "#2a1a05", "ecoli", 1671],
  ["parkville-phages", "The Parkville Phages", "Melbourne", "Melbourne", "Australia", "AU", -37.8, 145.0, "#0b6b45", "#04201a", "strep", 1699],
  ["ontario-operons", "The Ontario Operons", "Toronto", "Toronto", "Canada", "CA", 43.7, -79.4, "#d52b1e", "#2a0a08", "acineto", 1716],
  ["paulista-pseudomonads", "The Paulista Pseudomonads", "USP São Paulo", "São Paulo", "Brazil", "BR", -23.5, -46.6, "#2ecc71", "#07261a", "pseudo", 1739],
  ["gwanak-gradients", "The Gwanak Gradients", "Seoul National", "Seoul", "South Korea", "KR", 37.5, 127.0, "#00a86b", "#052a1e", "acineto", 1683],
];

const MOTTOS = [
  "Grow where others clear.",
  "Every plate a proof.",
  "Wild type, wild heart.",
  "Ferment. Measure. Repeat.",
  "Clear the field.",
  "Nothing is lost that is sequenced.",
  "Select for the brave.",
  "A halo is a promise.",
  "Yield is everything.",
  "One colony at a time.",
  "Diffuse, then decide.",
  "Oxidise the doubt.",
  "Pass it on.",
  "Ten-fold, fearless.",
  "Follow the gradient.",
  "Sweet on glucose.",
  "Break it open.",
  "Colonise kindly.",
  "Titrate to the truth.",
  "Copy, paste, express.",
  "Infect the status quo.",
  "Read the operon.",
  "Green means grow.",
  "Steep is good.",
];

const PI_NAMES = [
  "Dr. A. Reyes", "Dr. M. Sørensen", "Dr. J. de Vries", "Dr. L. Brunner",
  "Dr. P. Whitfield", "Dr. K. Hartmann", "Dr. E. Lindqvist", "Dr. R. Takeda",
  "Dr. W. Zhao", "Dr. N. Tan", "Dr. S. Park", "Dr. H. Ashcroft",
  "Dr. T. Okafor", "Dr. F. Bakker", "Dr. C. Peeters", "Dr. O. Nilsson",
  "Dr. G. Moreau", "Dr. I. Salazar", "Dr. Z. Mokoena", "Dr. V. Iyer",
  "Dr. B. Chalmers", "Dr. D. Fortin", "Dr. A. Cardoso", "Dr. J. Kim",
];

export const HOUSES: House[] = HOUSE_SEEDS.map((h, i) => {
  const [slug, name, institution, city, country, countryCode, lat, lon, primary, secondary, signatureOrganism, elo] = h;
  const p = 6;
  const w = Math.max(0, Math.min(p, Math.round((elo - 1640) / 40)));
  const d = (i * 7) % 3;
  const l = Math.max(0, p - w - d);
  return {
    slug,
    name,
    institution,
    city,
    country,
    countryCode,
    lat,
    lon,
    founded: 2024 + (i % 3),
    motto: MOTTOS[i],
    primary,
    secondary,
    signatureOrganism,
    pi: PI_NAMES[i],
    members: 6 + ((i * 5) % 11),
    elo,
    division: elo >= 1720 ? "I" : "II",
    trophies: elo > 1800 ? ["Season II Antibiotic Cup"] : [],
    record: { p, w, d, l },
  };
});

export const CARDS: Card[] = [
  {
    id: "pyo-7",
    accession: "PYO-7",
    name: "Midnight Bloom",
    organism: "pseudo",
    houseSlug: "davidoffs",
    season: 3,
    rarity: "mythic",
    edition: "1 of 1",
    bsl: "BSL-1",
    keywords: ["SWARMING", "PYOCYANIN", "BIOFILM"],
    stats: { titer: 62, inhibition: 91, growth: 44, robust: 71, chroma: 97 },
    flavour: "It painted the whole plate before anyone noticed.",
    licence: "CC-BY-4.0",
    art: { agar: "#0a1a24", colony: "#2fe6d6", accent: "#7b5cff", pattern: "swarm", seed: 7 },
  },
  {
    id: "eco-12",
    accession: "ECO-12",
    name: "Ironside",
    organism: "ecoli",
    houseSlug: "lyngby-lysogens",
    season: 3,
    rarity: "epic",
    edition: "3 of 12",
    bsl: "BSL-1",
    keywords: ["FAST", "CHASSIS", "DEFINED MEDIA"],
    stats: { titer: 88, inhibition: 23, growth: 93, robust: 66, chroma: 12 },
    flavour: "Doubled before the lid was back on.",
    licence: "CC-BY-4.0",
    art: { agar: "#101a0c", colony: "#b8ff3c", accent: "#e8c46a", pattern: "colonies", seed: 12 },
  },
  {
    id: "str-3",
    accession: "STR-3",
    name: "Red Tide",
    organism: "strep",
    houseSlug: "kensington-kinetics",
    season: 3,
    rarity: "rare",
    edition: "8 of 40",
    bsl: "BSL-2",
    keywords: ["HEMOLYTIC", "BACTERIOCIN"],
    stats: { titer: 41, inhibition: 84, growth: 58, robust: 39, chroma: 55 },
    flavour: "Clears the room. Literally.",
    licence: "CC-BY-4.0",
    art: { agar: "#1c0a10", colony: "#ff3b5c", accent: "#ffb020", pattern: "halo", seed: 3 },
  },
  {
    id: "acb-9",
    accession: "ACB-9",
    name: "Dustwalker",
    organism: "acineto",
    houseSlug: "hongo-halos",
    season: 3,
    rarity: "mythic",
    edition: "1 of 1",
    bsl: "BSL-2",
    keywords: ["DESICCATION", "EFFLUX", "PERSISTER"],
    stats: { titer: 30, inhibition: 18, growth: 47, robust: 99, chroma: 34 },
    flavour: "Sat on the bench for a month. Still there.",
    licence: "CC-BY-4.0",
    art: { agar: "#1a1206", colony: "#ffb020", accent: "#ff3b5c", pattern: "rings", seed: 9 },
  },
  {
    id: "eco-41",
    accession: "ECO-41",
    name: "Glasshouse",
    organism: "ecoli",
    houseSlug: "wageningen-wildtypes",
    season: 3,
    rarity: "uncommon",
    edition: "22 of 120",
    bsl: "BSL-1",
    keywords: ["LAWN", "STABLE"],
    stats: { titer: 71, inhibition: 15, growth: 77, robust: 58, chroma: 20 },
    flavour: "Reproducible is a flex.",
    licence: "CC-BY-4.0",
    art: { agar: "#0e1a0a", colony: "#9be03a", accent: "#2fe6d6", pattern: "lawn", seed: 41 },
  },
  {
    id: "pyo-22",
    accession: "PYO-22",
    name: "Verdigris",
    organism: "pseudo",
    houseSlug: "kent-ridge-colonies",
    season: 3,
    rarity: "rare",
    edition: "5 of 40",
    bsl: "BSL-1",
    keywords: ["PYOVERDINE", "FLUORESCENT"],
    stats: { titer: 55, inhibition: 69, growth: 52, robust: 61, chroma: 88 },
    flavour: "Glows under the UV lamp like it wants to be found.",
    licence: "CC-BY-4.0",
    art: { agar: "#071a14", colony: "#5cf0a8", accent: "#2fe6d6", pattern: "colonies", seed: 22 },
  },
  {
    id: "str-17",
    accession: "STR-17",
    name: "Lancefield",
    organism: "strep",
    houseSlug: "solna-selectors",
    season: 3,
    rarity: "epic",
    edition: "2 of 12",
    bsl: "BSL-2",
    keywords: ["HEMOLYTIC", "CHAIN-FORMING"],
    stats: { titer: 36, inhibition: 90, growth: 49, robust: 44, chroma: 47 },
    flavour: "Grouped, typed, and ready.",
    licence: "CC-BY-4.0",
    art: { agar: "#1a0b12", colony: "#ff5c7a", accent: "#e8c46a", pattern: "halo", seed: 17 },
  },
  {
    id: "acb-4",
    accession: "ACB-4",
    name: "Sandstone",
    organism: "acineto",
    houseSlug: "planck-plasmids",
    season: 3,
    rarity: "uncommon",
    edition: "31 of 120",
    bsl: "BSL-2",
    keywords: ["DESICCATION", "SLOW"],
    stats: { titer: 28, inhibition: 22, growth: 31, robust: 86, chroma: 29 },
    flavour: "Patience, measured in weeks.",
    licence: "CC-BY-4.0",
    art: { agar: "#1a1408", colony: "#e0a030", accent: "#6b7a8f", pattern: "colonies", seed: 4 },
  },
  {
    id: "eco-77",
    accession: "ECO-77",
    name: "Zymurgist's Pride",
    organism: "ecoli",
    houseSlug: "zurich-zymurgists",
    season: 3,
    rarity: "rare",
    edition: "11 of 40",
    bsl: "BSL-1",
    keywords: ["HIGH-TITER", "CHASSIS"],
    stats: { titer: 95, inhibition: 10, growth: 81, robust: 52, chroma: 18 },
    flavour: "Every gram accounted for.",
    licence: "CC-BY-4.0",
    art: { agar: "#0f1a0a", colony: "#c6ff5e", accent: "#ffffff", pattern: "lawn", seed: 77 },
  },
  {
    id: "pyo-31",
    accession: "PYO-31",
    name: "Deep Field",
    organism: "pseudo",
    houseSlug: "paulista-pseudomonads",
    season: 3,
    rarity: "epic",
    edition: "6 of 12",
    bsl: "BSL-1",
    keywords: ["PYOCYANIN", "ANTAGONIST"],
    stats: { titer: 48, inhibition: 87, growth: 60, robust: 63, chroma: 79 },
    flavour: "Blue on the third day. Blue forever.",
    licence: "CC-BY-4.0",
    art: { agar: "#08161f", colony: "#25c8c0", accent: "#2ecc71", pattern: "swarm", seed: 31 },
  },
];

export const CHALLENGES: Challenge[] = [
  {
    id: "c-1",
    slug: "pyocyanin-open",
    name: "The Pyocyanin Open",
    subtitle: "Season III flagship · Chroma × Antibiotic",
    track: "antibiotic-titer",
    organism: "pseudo",
    status: "open",
    submissionMode: "strain",
    closesAt: "2026-10-09T18:00:00Z",
    sealedRevealAt: "2026-10-30T18:00:00Z",
    entrants: 211,
    houses: 32,
    plates: 1280,
    prize: "Mythic foil · sponsored sequencing",
    sponsor: "Reshape Biotech",
    summary: "Inhibit the reference indicator with a pigmented Pseudomonas isolate. Public panel scores halo diameter; the sealed panel adds three undisclosed media.",
    scoring: "Halo diameter (mm), control-normalised, median of replicates.",
    publicConditions: 4,
    sealedConditions: 3,
    replicateFloor: 6,
    art: { agar: "#0a1a24", colony: "#2fe6d6", accent: "#7b5cff", pattern: "halo", seed: 101 },
  },
  {
    id: "c-2",
    slug: "media-cup-iii",
    name: "Media Cup III",
    subtitle: "Fixed strain · you bring the medium",
    track: "media-cup",
    organism: "ecoli",
    status: "open",
    submissionMode: "media",
    closesAt: "2026-10-16T18:00:00Z",
    sealedRevealAt: "2026-11-06T18:00:00Z",
    entrants: 96,
    houses: 24,
    plates: 480,
    prize: "Epic foil · cost-per-litre trophy",
    summary: "Fastest radial growth of the reference E. coli on your recipe. Cheap defined media that match rich broth score a complexity bonus.",
    scoring: "Radial growth rate (mm/h) × complexity multiplier.",
    publicConditions: 3,
    sealedConditions: 2,
    replicateFloor: 6,
    art: { agar: "#0f1a0a", colony: "#b8ff3c", accent: "#e8c46a", pattern: "lawn", seed: 102 },
  },
  {
    id: "c-3",
    slug: "iron-gut",
    name: "Iron Gut",
    subtitle: "Robustness · preservative panel",
    track: "robustness",
    organism: "acineto",
    status: "open",
    submissionMode: "strain",
    closesAt: "2026-10-23T18:00:00Z",
    sealedRevealAt: "2026-11-13T18:00:00Z",
    entrants: 64,
    houses: 18,
    plates: 720,
    prize: "Rare foil · robustness record",
    summary: "Survive a six-stress preservative panel with an avirulent Acinetobacter surrogate. Sealed panel adds two undisclosed stresses.",
    scoring: "Viable count retention (%) across the panel, geometric mean.",
    publicConditions: 6,
    sealedConditions: 2,
    replicateFloor: 4,
    art: { agar: "#1a1206", colony: "#ffb020", accent: "#ff3b5c", pattern: "rings", seed: 103 },
  },
  {
    id: "c-4",
    slug: "chroma-salon",
    name: "Chroma Salon",
    subtitle: "Bacterial art · jury-judged",
    track: "chroma",
    organism: "pseudo",
    status: "upcoming",
    submissionMode: "pairing",
    closesAt: "2026-11-20T18:00:00Z",
    sealedRevealAt: "2026-12-04T18:00:00Z",
    entrants: 0,
    houses: 0,
    plates: 320,
    prize: "Mythic foil · gallery feature",
    summary: "Timelapse beauty. Colour area, saturation and pattern entropy are measured; a jury adds the final modifier.",
    scoring: "Colour-area × saturation × entropy, plus jury modifier.",
    publicConditions: 2,
    sealedConditions: 1,
    replicateFloor: 3,
    art: { agar: "#0c0a1f", colony: "#7b5cff", accent: "#2fe6d6", pattern: "swarm", seed: 104 },
  },
];

const mkCurve = (n: number, peak: number, lag: number) =>
  Array.from({ length: n }, (_, i) => Math.round(peak / (1 + Math.exp(-(i - lag) / (n / 9)))));

export const FIXTURES: Fixture[] = [
  {
    id: "f-301",
    competition: "season-iii",
    group: "C",
    matchday: 3,
    status: "live",
    track: "antibiotic-titer",
    elapsedHours: 18,
    totalHours: 48,
    kickoff: "2026-09-26T08:00:00Z",
    replicates: 6,
    controlDrift: 2.1,
    home: { houseSlug: "davidoffs", cardId: "pyo-7", score: 34, cfu: 473, mumax: 0.42, curve: mkCurve(24, 36, 8) },
    away: { houseSlug: "lyngby-lysogens", cardId: "eco-12", score: 27, cfu: 388, mumax: 0.51, curve: mkCurve(24, 29, 7) },
    commentary: [
      { at: "18:22", text: "Pyocyanin front reaches the inhibition edge", kind: "event" },
      { at: "12:04", text: "Davidoff replicate 4 voided (lid condensation)", kind: "void" },
    ],
  },
  {
    id: "f-302",
    competition: "season-iii",
    group: "A",
    matchday: 3,
    status: "live",
    track: "arena",
    elapsedHours: 31,
    totalHours: 48,
    kickoff: "2026-09-25T20:00:00Z",
    replicates: 6,
    controlDrift: 1.4,
    home: { houseSlug: "kensington-kinetics", cardId: "str-3", score: 512, cfu: 512, mumax: 0.38, curve: mkCurve(24, 540, 10) },
    away: { houseSlug: "hongo-halos", cardId: "acb-9", score: 498, cfu: 498, mumax: 0.33, curve: mkCurve(24, 530, 12) },
    commentary: [],
  },
  {
    id: "f-303",
    competition: "season-iii",
    group: "E",
    matchday: 3,
    status: "final",
    track: "sprint",
    elapsedHours: 24,
    totalHours: 24,
    kickoff: "2026-09-25T08:00:00Z",
    replicates: 6,
    controlDrift: 0.9,
    home: { houseSlug: "zurich-zymurgists", cardId: "eco-77", score: 0.61, cfu: 0, mumax: 0.61, curve: mkCurve(24, 61, 6) },
    away: { houseSlug: "wageningen-wildtypes", cardId: "eco-41", score: 0.57, cfu: 0, mumax: 0.57, curve: mkCurve(24, 57, 7) },
    commentary: [],
  },
  {
    id: "f-304",
    competition: "season-iii",
    group: "G",
    matchday: 3,
    status: "scheduled",
    track: "antibiotic-titer",
    elapsedHours: 0,
    totalHours: 48,
    kickoff: "2026-09-28T08:00:00Z",
    replicates: 6,
    controlDrift: 0,
    home: { houseSlug: "paulista-pseudomonads", cardId: "pyo-31", score: 0, cfu: 0, mumax: 0, curve: [] },
    away: { houseSlug: "solna-selectors", cardId: "str-17", score: 0, cfu: 0, mumax: 0, curve: [] },
    commentary: [],
  },
];

export const STREAMS: Stream[] = [
  {
    id: "s-1",
    title: "Incubator rack · 24/7 timelapse",
    channel: "microwar",
    live: true,
    viewers: 1284,
    kind: "ambient",
    startsAt: "2026-09-01T00:00:00Z",
    art: { agar: "#0a1a24", colony: "#2fe6d6", accent: "#b8ff3c", pattern: "colonies", seed: 900 },
  },
  {
    id: "s-2",
    title: "Match Day 3 Live · Group C",
    channel: "microwar",
    live: true,
    viewers: 3412,
    kind: "match",
    startsAt: "2026-09-27T12:00:00Z",
    art: { agar: "#0a1a24", colony: "#2fe6d6", accent: "#7b5cff", pattern: "halo", seed: 901 },
  },
  {
    id: "s-3",
    title: "Plate pour: defined media from scratch",
    channel: "lyngby-lysogens",
    live: false,
    viewers: 0,
    kind: "howto",
    houseSlug: "lyngby-lysogens",
    startsAt: "2026-09-29T16:00:00Z",
    art: { agar: "#0f1a0a", colony: "#b8ff3c", accent: "#e8c46a", pattern: "lawn", seed: 902 },
  },
  {
    id: "s-4",
    title: "Sealed Panel Reveal · The Pyocyanin Open",
    channel: "microwar",
    live: false,
    viewers: 0,
    kind: "reveal",
    startsAt: "2026-10-30T18:00:00Z",
    art: { agar: "#0c0a1f", colony: "#7b5cff", accent: "#2fe6d6", pattern: "swarm", seed: 903 },
  },
];

export const TICKER: TickerItem[] = [
  { id: "t-1", houseSlug: "davidoffs", text: "34 mm halo · PYO-7", value: "+3.1", direction: "up" },
  { id: "t-2", houseSlug: "lyngby-lysogens", text: "µmax 0.51 · ECO-12", value: "+0.02", direction: "up" },
  { id: "t-3", houseSlug: "kensington-kinetics", text: "CFU 512 · STR-3", value: "−14", direction: "down" },
  { id: "t-4", houseSlug: "hongo-halos", text: "robust 99 · season record", value: "★", direction: "up" },
  { id: "t-5", houseSlug: "zurich-zymurgists", text: "wins Sprint MD3", value: "3 pts", direction: "up" },
  { id: "t-6", houseSlug: "wageningen-wildtypes", text: "replicate spread 4.2%", value: "ok", direction: "flat" },
  { id: "t-7", houseSlug: "paulista-pseudomonads", text: "PYO-31 accessioned", value: "QC ✓", direction: "flat" },
  { id: "t-8", houseSlug: "solna-selectors", text: "STR-17 plated · 6 reps", value: "48h", direction: "flat" },
  { id: "t-9", houseSlug: "kent-ridge-colonies", text: "chroma 88 · PYO-22", value: "+6", direction: "up" },
  { id: "t-10", houseSlug: "planck-plasmids", text: "Iron Gut entry received", value: "n=4", direction: "flat" },
  { id: "t-11", houseSlug: "oxford-oxidants", text: "drops to Division II", value: "▼", direction: "down" },
  { id: "t-12", houseSlug: "tsinghua-titers", text: "titer 95 · ECO-77 tied", value: "=", direction: "flat" },
];
